spring:
  application:
    name: employee-main-app
  mvc: 
    view: 
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    
server:
  port: 8082
  
  
logging: 
  level: 
    org: 
      springframework: TRACE
    com: TRACE