spring:
  application:
    name: zuul-service

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
        defaultZone: https://eureka-service-dev.cfapps.io/eureka/
  instance:
    hostname: ${vcap.application.uris[0]}
    nonSecurePort: 80
    appname: zuul-service
     

zuul:
  sensitive-headers: Cookie,Set-Cookie
  ignoredServices: "*"
  routes:
    employee-master-service: 
      path: /dashboard/**
      serviceId: employee-master-service
      stripPrefix: false
    employee-master-service-feign: 
      path: /dashboard-feign/**
      serviceId: employee-master-service
      stripPrefix: false
    employee-details-service: 
      path: /employee/**
      serviceId: employee-details-service
      stripPrefix: false
    employee-hierarchy-service: 
      path: /manager/**
      serviceId: employee-hierarchy-service
      stripPrefix: false
  host:
    socket-timeout-millis: 10000 
    connect-timeout-millis: 10000
    
  