server:
  port: 9000
  servlet:
    context-path: /service


security:
  oauth2:
    client:
      client-id: employeeapp
      client-secret: pass
      authorized-grant-types: authorization_code,refresh_token,password
      scope: openid



             